name = "Vector2"
doc = """
A built-in type representing 2D coordinates, either as a point or as a vector.
"""

[[member]]
def = """
    /// The X coordinate.
    double x;
"""

[[member]]
def = """
    /// The Y coordinate.
    double y;
"""

[[function]]
def = """
    /// Returns the length (magnitude) of the vector.
    double Length() const;
"""

[[function]]
def = """
    /// Returns a normalized vector. Equivalent to `vec /
    /// vec.Length()`.
    Vector2 Unit() const;
"""
