name = "Vector3"
doc = """
A built-in type representing 3D coordinates, either as a point or as a vector.
"""

[[member]]
def = """
    /// The X coordinate.
    double x;
"""

[[member]]
def = """
    /// The Y coordinate.
    double y;
"""

[[member]]
def = """
    /// The Z coordinate.
    double z;
"""

[[member]]
def = """
    /// The X and Y coordinates as a [`Vector2`].
    ///
    /// This is not a unique piece of data and "overlaps" with [`x`]
    /// and [`y`]. Modifying this will modify them.
    transient Vector2 xy;
"""

[[function]]
def = """
    /// Returns the length (magnitude) of the vector.
    double Length() const;
"""

[[function]]
def = """
    /// Returns a normalized vector. Equivalent to `vec /
    /// vec.Length()`.
    Vector3 Unit() const;
"""
